apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: pvc-cc-4  
        namespace: newgen
spec:

        volumeMode: Filesystem
        accessModes:
                   - ReadWriteOnce
        resources:
               requests:                
                        storage: 4Gi
        storageClassName: external-nfs
                                
