apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: pvc-nfs.pvc-2
        namespace: newgen
spec:
        volumeMode: Filesystem
        accessModes:    
                - ReadWriteOnce
        resources:
                requests:       
                     storage: 4Gi
        storageClassName: nfs-client 
