apiVersion: apps/v1
kind: Deployment
metadata:
        name: nfsstroage-deployment3
        namespace: newgen
        labels:
                app: new4
spec:
        template:
                metadata:
                         name: nfsstroage-deployment3
                         labels:
                                app: new4
                spec:
                        containers:
                               - name: nginx
                                 image: nginx
                                 volumeMounts:
                                         - name: my-firest-3
                                           mountPath: /mnt
                        volumes:
                                - name: my-firest-3
                                  persistentVolumeClaim:
                                                claimName: pvc-cc-1

        replicas: 3
        selector:
                matchLabels:
                        app: new4
