apiVersion: apps/v1
kind: Deployment
metadata:
        name: nfsstroage-deployment5
        namespace: newgen
        labels:
                app: new6
spec:
        template:
                metadata:
                         name: nfsstroage-deployment5
                         labels:
                                app: new6
                spec:
                        containers:
                               - name: nginx
                                 image: nginx
                                 volumeMounts:
                                         - name: my-firest-5
                                           mountPath: /mnt
                        volumes:
                                - name: my-firest-5
                                  persistentVolumeClaim:
                                                claimName: pvc-cc-4 

        replicas: 3
        selector:
                matchLabels:
                        app: new6
