apiVersion: apps/v1
kind: Deployment
metadata:
         name: secretmysql1
         namespace: newgen
         labels:
                app: secretmysqlapp
spec:
        template:
                metadata:
                        labels:
                                app: secretmysqlapp
                spec:
                        containers:
                                - name: mysql
                                  image: mysql
                                  env:
                                       - name: USERNAMEDIR1
                                         valueFrom:
                                              secretKeyRef:
                                                        name: secretmysql1      
                                                        key: username
                                         
                                       - name: PASSWORDIR1
                                         valueFrom:
                                              secretKeyRef:
                                                        name: secretmysql1
                                                        key: password


                                  args:
                                    - /bin/sh
                                    - -c
                                    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
                                  livenessProbe:
                                      exec:
                                              command:
                                                     - cat
                                                     - /tmp/healthy
                                      initialDelaySeconds: 5
                                      periodSeconds: 5


                                  volumeMounts:
                                              - name: mynfsvoldir1 
                                                mountPath: /mnt


                                              - name: myvoldir1
                                                mountPath: /tmp
                        volumes:
                                - name: mynfsvoldir1
                                  persistentVolumeClaim:
                                                  claimName: newdir1pvc 

                                - name: myvoldir1
                                  secret:
                                        secretName: secretmysql1



        replicas: 2
        selector        :
                matchLabels:
                        app: secretmysqlapp

