apiVersion: apps/v1
kind: Deployment
metadata:
        name: nginx-deploy-1
        namespace: newgen
        labels:
                ap: ng-1
spec:
       template:
                metadata:
                        labels:
                                ap: ng-1
                spec:
                        containers:
                                - name: nginx
                                  image: nginx
                                  volumeMounts:
                                                - name: nginx-vol-1
                                                  mountPath: /etc/nginx 
                        volumes:
                                - name: nginx-vol-1
                                  configMap:
                                             name: nginxconfigmap1
                                             items:
                                                        - key: nginx.conf       
                                                          path: nginx.conf
                                                        - key: virtualhost.conf
                                                          path: virtualhost/virtualhost.conf
                                

       replicas: 1
       selector:
                matchLabels:
                                ap: ng-1
