apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity-nginx
  namespace: caas
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: color
            operator: DoesNotExist
          - key: food
            operator: DoesNotExist
  containers:
     - name: with-node-affinity-nginx
       image: nginx
