apiVersion: v1
kind: PersistentVolume
metadata:
        name: newdir1pv 
spec:
        capacity:
                storage: 5Gi
        accessModes:
                        - ReadWriteMany
        volumeMode:     Filesystem
        persistentVolumeReclaimPolicy: Retain
        storageClassName: newdirnfs1
        mountOptions:
               - hard
               - nfsvers=4.1
        nfs:
                server: 10.0.0.4
                path: /newdir1/share1
        claimRef:
                name: newdir1pvc
                namespace: newgen
                 
