apiVersion: v1
kind: PersistentVolume
metadata:
        name: nfsc4
        namespace: newgen
spec:
        capacity:
                storage: 5Gi
        volumeMode:  Filesystem
        accessModes:
                - ReadWriteOnce
        persistentVolumeReclaimPolicy: Delete
        storageClassName: external-nfs
        mountOptions:
                - hard
                - nfsvers=4.1
        nfs:
              path: /storageshare/backup
              server: 10.0.0.4

        claimRef:
                name: pvc-cc-4
                namespace: newgen
