apiVersion: v1
kind: PersistentVolume
metadata:
        name: nfspv1
        namespace: newgen
spec:
        capacity:
                storage: 5Gi
        volumeMode:  Filesystem
        accessModes:
                - ReadWriteOnce
        persistentVolumeReclaimPolicy: Retain
        storageClassName: nfs-pv-share1
        mountOptions:
                - hard
                - nfsvers=4.1
        nfs:
              path: /newshare
              server: 10.0.0.4

        claimRef:
                name: pvc-nfs-2
                namespace: newgen
