apiVersion: v1
kind: PersistentVolume
metadata:
        name: new-pv
spec:
        capacity:
                storage: 5Gi
        volumeMode:   Filesystem
        accessModes:
                - ReadWriteOnce
        persistentVolumeReclaimPolicy: Retain
        storageClassName: nfs-client
        mountOptions:
                - hard
                - nfsvers=4.1
        nfs:
            server: 10.0.0.4
            path: /storageshare 
        claimRef:
                name: pvc-nfs.pvc-1
                namespace: newgen

                        
