apiVersion: v1
kind: PersistentVolume
metadata:
        name: sharedeplomentdir2
spec:
        capacity:
                storage:  5Gi
        volumeMode: Filesystem
        accessModes:
                        - ReadWriteMany
        storageClassName: storagenfs-2
        persistentVolumeReclaimPolicy: Retain
        mountOptions:
                - hard
                - nfsvers=4.1
        nfs:
               path: /sharedeployment/dir2
               server: 10.0.0.4
        claimRef:
                name: sharedeploymentpvc-dir2
                namespace: newgen 
