apiVersion: v1
kind: PersistentVolume
metadata:
        name: new-pv1
spec:
        capacity:
                storage: 5Gi
        volumeMode:   Filesystem
        accessModes:
                - ReadWriteOnce
        persistentVolumeReclaimPolicy: Retain
        storageClassName: nfs-client
        mountOptions:
                - hard
                - nfsvers=4.1
        nfs:
            server: 10.0.0.4
            path: /storageshare/volume 
        claimRef:
                name: pvc-nfs.pvc-2
                namespace: newgen

                        
