apiVersion: v1
kind: Service
metadata:
        name: clusteripsharedeploymentdir1
        namespace: newgen
spec:
        selector: 
                app: sharedeploymentdir1label
        ports:
                - name: centos-deploymentdir1
                  port: 2223
                  targetPort: 22

                - name: centos-deploymentdir2
                  port: 2224
                  targetPort: 22

