apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec: 
  containers:
  - name: private-reg-container
    image:  aadikapoor23/first-repo:web2
  imagePullSecrets:  
  - name: docker-secret-register
