apiVersion: v1
kind: Secret
metadata:
        name: nignxsecret1
        namespace: newgen
        
type: Opaque   
data:
        nginxusername1: a3VsZGVlcAo=
        nginxpassword: cmVkaGF0Cg==

        hello.txt: |

        gamefirst: a3VsZGVlcAo=
        gamesecond: a3VsZGVlcAo=

        hi.txt: |

        gamehifirst: a3VsZGVlcAo=
        gamehisecond: a3VsZGVlcAo=


