apiVersion: v1
kind: Secret
metadata:
        name: tlssecret
        namespace: newgen

type:   kubernetes.io/tls
data:
        tls.crt: |
                
                LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Fo
                a2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1UQXhN
                REE1TlRrek5sb1hEVE14TVRBd09EQTVOVGt6Tmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVa
                WFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTXhhCk9rUGVY
                RDJmRkJwUk1GOHhiVE1RNWQrZ0NnR0JkbS9IMFNkOHNxNUJveSt4YytDa3FiWmU3a0NrYjFPamZV
                N0EKNHQ4cmlqb2w3cmMwemRlZXlObVU1ZkMweHc0T3lVS1Q1TG9ZdmJxZ0U1ZTlSWEpwK014eGRL
                RjdDOXpoblJkTQpURTRqaVVXOC93c2xyR01MODNnWmYxNmgxbE5FaWlLclAycXY1Y2hHRDQwTDB3
                dEtlVHNMNFlNVC9YOXpBNE1DClZmVTJlZFpMeU9rMzFCUnpVSytUK0M2TzBuZFVrUmZIUEJ2OG4r
                Yk5aUnd4VXVYUDJLZWs3L3puSVI1SXJhOTkKNC84bmRyb2VwQVpMai9YdGVKSmkwZVdrb0g0WGlJ
                ZHE1VGNrRTIrbEZlQXhucnJBOXpGUWR3dUt3eWVrMEx1VAowaGNaOU01ek5xaW9WUzFObHE4Q0F3
                RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RR
                WUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFDNjU2WmNwRGpSUGdOWG5yckU0eFFYcUxJVHUKZWJYS1ZL
                RDJveW5BWFVuNi9vTXIyMVBmVC91aTVMOHZpeFQweWw0WmF0NEZDV2g3ekFHUFZaQko3SkoveXR0
                SQpxc3Y1L3UrSll6M21KTUUzbUN1eUs1blU2ekQveENWUS9xZ0Rjc3B4TEw1QjlDR05MUjlJY0ll
                WjNBZENIZ2JKCkdrNFM1UE9BT0lNMWhIOWZ5V1hCMTZSK28zYUZHcnRIRld6aFFTcVdnQkJ3YTF5
                SlNWWkpHak1iNE80ZS8vd3kKNFdudzVEQUhtV0R1OStnbEFJdGxDOFVMeTMyQktzS3JNckd3UXRj
                bDAwYnF0VENFd09FOW5mazl6NWJjUGlFRQp1S1hGV3RVbjNBL05uZ1loa05VU2hTYUUraENEVDNL
                dHNtOUdSazFMVUU5OTJmNHRJTU5WMlNxWXJUdz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=

        tls.key: |
                LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBekZvNlE5NWNQ
                WjhVR2xFd1h6RnRNeERsMzZBS0FZRjJiOGZSSjN5eXJrR2pMN0Z6CjRLU3B0bDd1UUtSdlU2TjlU
                c0RpM3l1S09pWHV0elROMTU3STJaVGw4TFRIRGc3SlFwUGt1aGk5dXFBVGw3MUYKY21uNHpIRjBv
                WHNMM09HZEYweE1UaU9KUmJ6L0N5V3NZd3Z6ZUJsL1hxSFdVMFNLSXFzL2FxL2x5RVlQalF2VApD
                MHA1T3d2aGd4UDlmM01EZ3dKVjlUWjUxa3ZJNlRmVUZITlFyNVA0TG83U2QxU1JGOGM4Ry95ZjVz
                MWxIREZTCjVjL1lwNlR2L09jaEhraXRyMzNqL3lkMnVoNmtCa3VQOWUxNGttTFI1YVNnZmhlSWgy
                cmxOeVFUYjZVVjRER2UKdXNEM01WQjNDNHJESjZUUXU1UFNGeG4wem5NMnFLaFZMVTJXcndJREFR
                QUJBb0lCQUg3Vi9kWUVITkp1ZTBhKwpYN3lsNi9aSEpiYUFHZFhIYWlDRk1FOUcrWXhvMXdXU0th
                OGo1T1o1MDMweDBwdGlIVE9WU3Z0amhkOERqa0FPCk9UajhxQU5NaE0rN0ZOV24zY2xDRERScGlO
                RmQ2K3RCb2VvYTFqN21xSkpWMGc0ZHhxZ2dSamcxbkUwNXVqOUwKK2N4Y0xaaThrcTdFMmtkQ2dr
                NTBaZDh0SC8wR1NzcFVEWGFsQk5PUW5pdERoUHZ5aGY4aXZ3dDlnSk0zUDUxVwplY21WUEYwYUc3
                KzFKTFA2UnI5YzdrUjdsaFZYdFhXTUk5WDQxZU4xQ3ViQVdMamtjeGJkWk9pcGNrOUtFMWJICkF3
                a29DUEJHblI4MUNkb1RhRS9pUlhxbEU1THlycDFsbjVrcCtqVSswR0l5eC9WYTBKSXIxQmE0S1ZY
                NGJQejIKa0h5S1VSa0NnWUVBOHhOeUx2RE5FZEVVbFlSU2phSGJ6OTV1Ky85R3pGYmkzczZrMlFh
                LzZlRXkyZXhHZG8xTApuTmRoRkF2a0RlZ0NaL3JxOWk2am11VVVQc0pOOGlkQW0reDBUWGVXV0Jj
                dU1YOWJ5TzFDcXJKdXhxUDdCbjZDCmpRUElwRHA0cFBSbU9OeW5KL2tnTzdSVEpCaTg1Slphay83
                NFRjSzlLN1JFS2hWNHR2OGorSXNDZ1lFQTF6ZTEKV0tQbUV2N3ExLzZSbXQyelltRmpVeC9keEJ5
                bzdzN0JpR1JtVUNRbWVGMG1kQll5VERmRU04d3dzaWxtcnp2aQozMVJxNU15L25UK1dhVTNXSVha
                TjVJRmxvMSs5eGt0Vnk4Y3dlaWd1SElibFp1QXRCSnMvNUFiSG4vK1c3K1RPCjdLZE1jUURqWW5Z
                NVFRMnJaWUdLWno1d3o2SlRicGZ2SWMwek91MENnWUVBd0I4emxhUmdBV0FHNi9KTktZS3YKOFFr
                M0lWZndSbHU2THk2WEhxMzJDODRoMmhxa3l0ajgxWGRxVkdUZG1Kd3pJcW94QWVsMUNGMWRkZ2t2
                Z0dERAo4VG1mNXdiSlB0RDdnc1hON3U2UVRjaUFRK0toNnMwZE5JVzBGUkhkLzByb2JMTUNMMWI1
                d2hiUnkrcjlpWkxJCi9zWjh6VUZKTVh6bWozaXZFN3h2V3VjQ2dZRUFoSDcwY3pTOElUZTFKdksv
                ZTJNLzI3SnZMcTZ3bmRxekdncEoKMVlsUi84YXh0R3BNa1MxVkc5MDlPbEpjTEdNV3A0MHIyQ2ds
                Z3VTV2x0MmQ0UWlkYW81bDErYmR4dDNiZktmRwpreVQzTUUxcVRmK3lYVXBvREt6emdaTzI5RWFy
                Q3RlSG1PUktTRXV1c1dCdFVTSjBRWktsdlhnUWhaTyszNWhFCkRVQkNhT1VDZ1lBT3g3cHJYZ0Iv
                cUlEaUFnTWRRcGtPaGlPK0l3ZTF6UlV4Z2VTVnNxdmR2MmdKb2grMm84NjkKck5zQnJwQ2Q1dnBR
                OG1qajk3eTVFS055ZVY3Rng2TGhBM1hudCtGNDdFY2dvNFI3aGk1YW1nazhucExOUnhzdQp6TkRP
                WHFvSnVzeTlzaDdPRGRDSnRzK2ZTUk1TeVZuakJsTlByYzNEV1JPaGJYelo3bUJFRFE9PQotLS0t
                LUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=

